// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package poset

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockSignature struct {
	Validator            []byte   `protobuf:"bytes,1,opt,name=Validator,proto3" json:"Validator,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	Signature            string   `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSignature) Reset()         { *m = BlockSignature{} }
func (m *BlockSignature) String() string { return proto.CompactTextString(m) }
func (*BlockSignature) ProtoMessage()    {}
func (*BlockSignature) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *BlockSignature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSignature.Unmarshal(m, b)
}
func (m *BlockSignature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSignature.Marshal(b, m, deterministic)
}
func (m *BlockSignature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSignature.Merge(m, src)
}
func (m *BlockSignature) XXX_Size() int {
	return xxx_messageInfo_BlockSignature.Size(m)
}
func (m *BlockSignature) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSignature.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSignature proto.InternalMessageInfo

func (m *BlockSignature) GetValidator() []byte {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *BlockSignature) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BlockSignature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type EventBody struct {
	Transactions         [][]byte          `protobuf:"bytes,1,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	Parents              []string          `protobuf:"bytes,2,rep,name=Parents,proto3" json:"Parents,omitempty"`
	Creator              []byte            `protobuf:"bytes,3,opt,name=Creator,proto3" json:"Creator,omitempty"`
	Index                int64             `protobuf:"varint,4,opt,name=Index,proto3" json:"Index,omitempty"`
	BlockSignatures      []*BlockSignature `protobuf:"bytes,5,rep,name=BlockSignatures,proto3" json:"BlockSignatures,omitempty"`
	SelfParentIndex      int64             `protobuf:"varint,6,opt,name=selfParentIndex,proto3" json:"selfParentIndex,omitempty"`
	OtherParentCreatorID int64             `protobuf:"varint,7,opt,name=otherParentCreatorID,proto3" json:"otherParentCreatorID,omitempty"`
	OtherParentIndex     int64             `protobuf:"varint,8,opt,name=otherParentIndex,proto3" json:"otherParentIndex,omitempty"`
	CreatorID            int64             `protobuf:"varint,9,opt,name=creatorID,proto3" json:"creatorID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *EventBody) Reset()         { *m = EventBody{} }
func (m *EventBody) String() string { return proto.CompactTextString(m) }
func (*EventBody) ProtoMessage()    {}
func (*EventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventBody.Unmarshal(m, b)
}
func (m *EventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventBody.Marshal(b, m, deterministic)
}
func (m *EventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventBody.Merge(m, src)
}
func (m *EventBody) XXX_Size() int {
	return xxx_messageInfo_EventBody.Size(m)
}
func (m *EventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_EventBody.DiscardUnknown(m)
}

var xxx_messageInfo_EventBody proto.InternalMessageInfo

func (m *EventBody) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *EventBody) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *EventBody) GetCreator() []byte {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *EventBody) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *EventBody) GetBlockSignatures() []*BlockSignature {
	if m != nil {
		return m.BlockSignatures
	}
	return nil
}

func (m *EventBody) GetSelfParentIndex() int64 {
	if m != nil {
		return m.SelfParentIndex
	}
	return 0
}

func (m *EventBody) GetOtherParentCreatorID() int64 {
	if m != nil {
		return m.OtherParentCreatorID
	}
	return 0
}

func (m *EventBody) GetOtherParentIndex() int64 {
	if m != nil {
		return m.OtherParentIndex
	}
	return 0
}

func (m *EventBody) GetCreatorID() int64 {
	if m != nil {
		return m.CreatorID
	}
	return 0
}

type EventCoordinates struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventCoordinates) Reset()         { *m = EventCoordinates{} }
func (m *EventCoordinates) String() string { return proto.CompactTextString(m) }
func (*EventCoordinates) ProtoMessage()    {}
func (*EventCoordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EventCoordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventCoordinates.Unmarshal(m, b)
}
func (m *EventCoordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventCoordinates.Marshal(b, m, deterministic)
}
func (m *EventCoordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventCoordinates.Merge(m, src)
}
func (m *EventCoordinates) XXX_Size() int {
	return xxx_messageInfo_EventCoordinates.Size(m)
}
func (m *EventCoordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_EventCoordinates.DiscardUnknown(m)
}

var xxx_messageInfo_EventCoordinates proto.InternalMessageInfo

func (m *EventCoordinates) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *EventCoordinates) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Index struct {
	ParticipantId        int64             `protobuf:"varint,1,opt,name=participantId,proto3" json:"participantId,omitempty"`
	Event                *EventCoordinates `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Index) Reset()         { *m = Index{} }
func (m *Index) String() string { return proto.CompactTextString(m) }
func (*Index) ProtoMessage()    {}
func (*Index) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *Index) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Index.Unmarshal(m, b)
}
func (m *Index) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Index.Marshal(b, m, deterministic)
}
func (m *Index) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Index.Merge(m, src)
}
func (m *Index) XXX_Size() int {
	return xxx_messageInfo_Index.Size(m)
}
func (m *Index) XXX_DiscardUnknown() {
	xxx_messageInfo_Index.DiscardUnknown(m)
}

var xxx_messageInfo_Index proto.InternalMessageInfo

func (m *Index) GetParticipantId() int64 {
	if m != nil {
		return m.ParticipantId
	}
	return 0
}

func (m *Index) GetEvent() *EventCoordinates {
	if m != nil {
		return m.Event
	}
	return nil
}

type Event struct {
	Body                 *EventBody `protobuf:"bytes,1,opt,name=Body,proto3" json:"Body,omitempty"`
	Signature            string     `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	TopologicalIndex     int64      `protobuf:"varint,3,opt,name=topologicalIndex,proto3" json:"topologicalIndex,omitempty"`
	Round                int64      `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	LamportTimestamp     int64      `protobuf:"varint,5,opt,name=lamportTimestamp,proto3" json:"lamportTimestamp,omitempty"`
	RoundReceived        int64      `protobuf:"varint,6,opt,name=roundReceived,proto3" json:"roundReceived,omitempty"`
	LastAncestors        []*Index   `protobuf:"bytes,7,rep,name=lastAncestors,proto3" json:"lastAncestors,omitempty"`
	FirstDescendants     []*Index   `protobuf:"bytes,8,rep,name=firstDescendants,proto3" json:"firstDescendants,omitempty"`
	creator              string     `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	hash                 []byte     `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
	hex                  string     `protobuf:"bytes,11,opt,name=hex,proto3" json:"hex,omitempty"`
	flagTable            []byte     `protobuf:"bytes,12,opt,name=FlagTable,proto3" json:"FlagTable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetBody() *EventBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Event) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Event) GetTopologicalIndex() int64 {
	if m != nil {
		return m.TopologicalIndex
	}
	return 0
}

func (m *Event) GetRound() int64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Event) GetLamportTimestamp() int64 {
	if m != nil {
		return m.LamportTimestamp
	}
	return 0
}

func (m *Event) GetRoundReceived() int64 {
	if m != nil {
		return m.RoundReceived
	}
	return 0
}

func (m *Event) GetLastAncestors() []*Index {
	if m != nil {
		return m.LastAncestors
	}
	return nil
}

func (m *Event) GetFirstDescendants() []*Index {
	if m != nil {
		return m.FirstDescendants
	}
	return nil
}

func (m *Event) GetCreator() string {
	if m != nil {
		return m.creator
	}
	return ""
}

func (m *Event) GetHash() []byte {
	if m != nil {
		return m.hash
	}
	return nil
}

func (m *Event) GetHex() string {
	if m != nil {
		return m.hex
	}
	return ""
}

func (m *Event) GetFlagTable() []byte {
	if m != nil {
		return m.flagTable
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockSignature)(nil), "poset.BlockSignature")
	proto.RegisterType((*EventBody)(nil), "poset.EventBody")
	proto.RegisterType((*EventCoordinates)(nil), "poset.EventCoordinates")
	proto.RegisterType((*Index)(nil), "poset.Index")
	proto.RegisterType((*Event)(nil), "poset.Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 516 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x3d, 0x6f, 0xdb, 0x30,
	0x10, 0x85, 0x4d, 0x2b, 0x8e, 0xce, 0x4e, 0x63, 0x10, 0x29, 0xca, 0xa1, 0x83, 0x20, 0x64, 0x10,
	0x0a, 0xd4, 0x83, 0xbb, 0x74, 0x28, 0x50, 0x34, 0x49, 0x0b, 0x78, 0x2b, 0x58, 0xa3, 0x53, 0x17,
	0x5a, 0x62, 0x6c, 0xa2, 0x32, 0x29, 0x90, 0x4c, 0x90, 0xfe, 0xa6, 0xfe, 0xab, 0xfe, 0x92, 0x82,
	0x47, 0xf9, 0x43, 0x4a, 0x36, 0xdd, 0xbb, 0x77, 0xc7, 0xe3, 0xbb, 0x47, 0xc1, 0x44, 0x3e, 0x4a,
	0xed, 0xe7, 0x8d, 0x35, 0xde, 0xd0, 0xa4, 0x31, 0x4e, 0xfa, 0x7c, 0x0d, 0xaf, 0x6e, 0x6a, 0x53,
	0xfe, 0xfe, 0xa1, 0x36, 0x5a, 0xf8, 0x07, 0x2b, 0xe9, 0x5b, 0x48, 0x7f, 0x8a, 0x5a, 0x55, 0xc2,
	0x1b, 0xcb, 0x06, 0xd9, 0xa0, 0x98, 0xf2, 0x23, 0x40, 0xaf, 0x20, 0x59, 0xea, 0x4a, 0x3e, 0xb1,
	0x61, 0x36, 0x28, 0x08, 0x8f, 0x41, 0xa8, 0x39, 0x34, 0x60, 0x24, 0x1b, 0x14, 0x29, 0x3f, 0x02,
	0xf9, 0xbf, 0x21, 0xa4, 0x5f, 0xc3, 0xd1, 0x37, 0xa6, 0xfa, 0x43, 0x73, 0x98, 0xae, 0xac, 0xd0,
	0x4e, 0x94, 0x5e, 0x19, 0xed, 0xd8, 0x20, 0x23, 0xc5, 0x94, 0x77, 0x30, 0xca, 0x60, 0xfc, 0x5d,
	0x58, 0xa9, 0xbd, 0x63, 0xc3, 0x8c, 0x14, 0x29, 0xdf, 0x87, 0x21, 0x73, 0x6b, 0x25, 0xce, 0x46,
	0x70, 0xb6, 0x7d, 0x78, 0x9c, 0x6c, 0x74, 0x3a, 0xd9, 0x67, 0xb8, 0xec, 0xde, 0xcf, 0xb1, 0x24,
	0x23, 0xc5, 0x64, 0xf1, 0x7a, 0x8e, 0x02, 0xcc, 0xbb, 0x59, 0xde, 0x67, 0xd3, 0x02, 0x2e, 0x9d,
	0xac, 0xef, 0xe3, 0xf9, 0xf1, 0x80, 0x33, 0x3c, 0xa0, 0x0f, 0xd3, 0x05, 0x5c, 0x19, 0xbf, 0x95,
	0x36, 0x62, 0xed, 0x58, 0xcb, 0x3b, 0x36, 0x46, 0xfa, 0x8b, 0x39, 0xfa, 0x0e, 0x66, 0x27, 0x78,
	0x6c, 0x7f, 0x8e, 0xfc, 0x67, 0x78, 0x10, 0xb9, 0x3c, 0x34, 0x4d, 0x91, 0x74, 0x04, 0xf2, 0x4f,
	0x30, 0x43, 0x8d, 0x6f, 0x8d, 0xb1, 0x95, 0xd2, 0xc2, 0x4b, 0x47, 0x29, 0x8c, 0xb6, 0xc2, 0x6d,
	0x71, 0x8b, 0x29, 0xc7, 0xef, 0x20, 0x93, 0x3a, 0x5d, 0x20, 0x06, 0xf9, 0xaf, 0x56, 0x3c, 0x7a,
	0x0d, 0x17, 0x8d, 0xb0, 0x5e, 0x95, 0xaa, 0x11, 0xda, 0x2f, 0x2b, 0xac, 0x25, 0xbc, 0x0b, 0xd2,
	0xf7, 0x90, 0xa0, 0x97, 0xb0, 0xc9, 0x64, 0xf1, 0xa6, 0xd5, 0xb2, 0x3f, 0x00, 0x8f, 0xac, 0xfc,
	0x2f, 0x81, 0x04, 0x73, 0xf4, 0x1a, 0x46, 0xc1, 0x04, 0xd8, 0x75, 0xb2, 0x98, 0x9d, 0xd6, 0x05,
	0x9c, 0x63, 0xb6, 0x6b, 0xa7, 0x61, 0xcf, 0x4e, 0x41, 0x33, 0x6f, 0x1a, 0x53, 0x9b, 0x8d, 0x2a,
	0x45, 0x1d, 0x35, 0x23, 0x51, 0xb3, 0x3e, 0x1e, 0x6e, 0x6b, 0xcd, 0x83, 0xae, 0xf6, 0xa6, 0xc0,
	0x20, 0x74, 0xa8, 0xc5, 0xae, 0x31, 0xd6, 0xaf, 0xd4, 0x4e, 0x3a, 0x2f, 0x76, 0x0d, 0x4b, 0x62,
	0x87, 0x3e, 0x1e, 0x04, 0xc1, 0x22, 0x2e, 0x4b, 0xa9, 0x1e, 0x65, 0xd5, 0x6e, 0xbf, 0x0b, 0xd2,
	0x05, 0x5c, 0xd4, 0xc2, 0xf9, 0x2f, 0xba, 0x94, 0xce, 0x1b, 0xeb, 0xd8, 0x18, 0x4d, 0x36, 0x6d,
	0x2f, 0x88, 0xc3, 0xf0, 0x2e, 0x85, 0x7e, 0x84, 0xd9, 0xbd, 0xb2, 0xce, 0xdf, 0x49, 0x57, 0x4a,
	0x5d, 0x89, 0xe0, 0xf6, 0xf3, 0x17, 0xca, 0x9e, 0xb1, 0xc2, 0x23, 0x68, 0x17, 0x8f, 0x3e, 0x48,
	0xf9, 0x3e, 0x3c, 0x6c, 0x1c, 0xf0, 0x6d, 0xc4, 0x8d, 0xcf, 0x80, 0x6c, 0xe5, 0x13, 0x9b, 0x20,
	0x33, 0x7c, 0x06, 0x7d, 0xbf, 0xd5, 0x62, 0xb3, 0x12, 0xeb, 0x5a, 0xb2, 0x69, 0x7c, 0xe2, 0x07,
	0x60, 0x7d, 0x86, 0x3f, 0x88, 0x0f, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x85, 0xd0, 0xee, 0x3f,
	0x2f, 0x04, 0x00, 0x00,
}
